/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shuffle;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yaron
 */
public class delete extends javax.swing.JFrame {

    Dimension d = new Dimension(); // the window appears in the middle of the screen
    Toolkit t = Toolkit.getDefaultToolkit(); // the window appears in the middle of the screen
    int x, y; // the window appears in the middle of the screen
    String path;

    /**
     * Creates new form gui
     */
    public delete(String path) {
        super("delete");
        initComponents();
        x = t.getScreenSize().width;
        y = t.getScreenSize().height;
        this.setLocation(x / 2 - (this.getSize().width), y / 2 - (this.getSize().height));
        this.path = path;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DelTA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DeleteB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("shuffle");

        jLabel1.setText("files numbers to delete:");

        DeleteB.setText("Delete");
        DeleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(DelTA, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteB)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(DeleteB)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBActionPerformed
        String FilesNum = DelTA.getText();
        String[] numbersBeforeRange = FilesNum.split(",");
        String[] numbers = new String[numbersBeforeRange.length];
        int j = 0;
        for (int i = 0; i < numbersBeforeRange.length; i++) {
            try {
                int num = Integer.parseInt(numbersBeforeRange[i]);
                numbers[j++] = "" + num;
            } catch (NumberFormatException e) {
                String[] range = numbersBeforeRange[i].split("-");
                if (range.length == 2) {
                    int rng = Integer.parseInt(range[1]) - Integer.parseInt(range[0]) + 1;
                    int start = Integer.parseInt(range[0]);
                    String[] NewNumbers = new String[numbers.length + (rng) - 1];
                    for (int k = 0; k < numbers.length; k++) {
                        NewNumbers[k] = numbers[k];
                    }
                    numbers = NewNumbers;
                    for (int k = 0; k < rng; k++) {
                        numbers[j++] = "" + start++;
                    }
                } else {
                    try {
                        throw new Exception("Error");
                    } catch (Exception ex) {
                        Logger.getLogger(delete.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        System.out.println(Arrays.toString(numbers));
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();

        for (int i = 0; i < listOfFiles.length; i++) {
            for (int k = 0; k < numbers.length; k++) {
                if (listOfFiles[i].isFile()) {
                    String newPath = listOfFiles[i].getAbsolutePath();
                    String[] arr = newPath.split("\\\\");
                    String[] temp = arr[arr.length - 1].split("-");
                    if(temp[0].equals(numbers[k])){
                        File del = new File(newPath);
                        try {
                            Files.delete(del.toPath());
                        } catch (IOException ex) {
                            Logger.getLogger(delete.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_DeleteBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DelTA;
    private javax.swing.JButton DeleteB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
